apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    istio-injection: "enabled"
    topology.istio.io/network: "network2"
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
