apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-server
  name: test-server-cluster01
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: test-server
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-server
  name: test-server-cluster02
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  type: ClusterIP
  