apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: default
  sources:
  - chart: base
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.27.1
  - chart: istiod
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.27.1
    # helm:
    #   releaseName: sealed-secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system